name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    env:
      PYTHONPATH: ${{ github.workspace }}
      TESTING: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Show Python & pip
        run: |
          python -V
          pip -V

      - name: Install deps
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # fallback, если нет requirements-файлов
          pip install \
            fastapi starlette jinja2 httpx uvicorn \
            sqlalchemy aiosqlite pydantic \
            pytest pytest-asyncio \
            black isort flake8 mypy

      - name: Lint - black
        run: black --check .

      - name: Lint - isort
        run: isort --check-only .

      - name: Lint - flake8
        run: flake8 .

      - name: Type check - mypy
        run: mypy .

      - name: Show workspace layout
        run: |
          pwd
          ls -la
          echo "----- tree (3 levels) -----"
          sudo apt-get update >/dev/null 2>&1 && sudo apt-get install -y tree >/dev/null 2>&1 || true
          tree -L 3 || true

      - name: Sanity import
        run: |
          python - <<'PY'
          import sys, os
          print("CWD:", os.getcwd())
          print("sys.path[:3]:", sys.path[:3])
          print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
          import importlib
          mod = importlib.import_module("hw1.main")
          print("Imported hw1.main; has app:", hasattr(mod, "app"))
          PY

      - name: Run tests - pytest (explicit path with verbose)
        run: |
          set -xe
          pytest -vv -ra -s hw1/tests


